import { NextRequest, NextResponse } from 'next/server';
import { pool } from '@/lib/pool';
import { fetchDinner } from '@/lib/dinners';
import { sendEmail } from '@/lib/email';
import InviteEmail from '@/emails/InviteEmail';
import { format } from 'date-fns';

interface SendResult {
  sent: number;
  skipped: number;
  failed: { guestId: number; reason: string }[];
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const { guestIds } = await request.json();

    if (!Array.isArray(guestIds) || guestIds.length === 0) {
      return NextResponse.json(
        { error: 'guestIds array is required' },
        { status: 400 }
      );
    }

    // Fetch dinner details
    const dinner = await fetchDinner(id);

    if (!dinner.fields['Dinner Date']) {
      return NextResponse.json(
        { error: 'Dinner date is required' },
        { status: 400 }
      );
    }

    const dinnerDate = new Date(dinner.fields['Dinner Date'] + 'T00:00:00');
    const formattedDate = format(dinnerDate, 'EEEE, MMMM do');
    const formattedTime = dinner.fields['Start Time']
      ? format(new Date(`2000-01-01T${dinner.fields['Start Time']}`), 'h:mm a')
      : '6:00 PM';
    const priceDollars = (dinner.fields['Price Cents'] || 4000) / 100;
    const websiteBaseUrl = process.env.WEBSITE_BASE_URL || 'https://con-vive.com';

    // Get host first name
    let hostFirstName = 'Your Host';
    if (dinner.fields['Host Guest ID']) {
      const hostResult = await pool.query(
        'SELECT first_name FROM guests WHERE id = $1',
        [dinner.fields['Host Guest ID']]
      );
      if (hostResult.rows.length > 0) {
        hostFirstName = hostResult.rows[0].first_name || hostFirstName;
      }
    } else if (dinner.host?.fields['First Name']) {
      hostFirstName = dinner.host.fields['First Name'];
    }

    // Fetch guest details
    const guestsResult = await pool.query(`
      SELECT id, first_name, email
      FROM guests
      WHERE id = ANY($1::int[])
    `, [guestIds]);

    const guestMap = new Map(
      guestsResult.rows.map(row => [row.id, { firstName: row.first_name, email: row.email }])
    );

    // Check existing invitations (non-declined)
    const existingResult = await pool.query(`
      SELECT guest_id FROM invitations
      WHERE dinner_id = $1 AND guest_id = ANY($2::int[])
        AND (status IS NULL OR status != 'declined')
    `, [id, guestIds]);

    const existingIds = new Set(existingResult.rows.map(r => r.guest_id));

    const result: SendResult = {
      sent: 0,
      skipped: 0,
      failed: [],
    };

    // Process each guest
    for (const guestId of guestIds) {
      // Skip if already invited
      if (existingIds.has(guestId)) {
        result.skipped++;
        continue;
      }

      const guest = guestMap.get(guestId);
      if (!guest) {
        result.failed.push({ guestId, reason: 'Guest not found' });
        continue;
      }

      // Skip if no email
      if (!guest.email) {
        result.failed.push({ guestId, reason: 'No email address' });
        continue;
      }

      try {
        // Create invitation record with token generated by PostgreSQL
        const insertResult = await pool.query(`
          INSERT INTO invitations (
            dinner_id,
            guest_id,
            status,
            token,
            invite_email_sent_at,
            invite_sent_date
          ) VALUES ($1, $2, 'invited', encode(gen_random_bytes(16), 'hex'), NOW(), CURRENT_DATE)
          RETURNING token
        `, [id, guestId]);

        const token = insertResult.rows[0].token;
        const bookingLink = `${websiteBaseUrl}/d/${token}`;

        // Send email
        const emailResult = await sendEmail({
          to: guest.email,
          subject: `You're invited to a Con-Vive dinner on ${formattedDate}`,
          react: InviteEmail({
            guestFirstName: guest.firstName || 'Friend',
            dinnerDate: formattedDate,
            dinnerTime: formattedTime,
            hostFirstName,
            menu: dinner.fields['Menu'] || 'A delicious dinner prepared with care',
            vibeDescriptor: dinner.fields['Vibe Descriptor'],
            priceDollars,
            magicLink: bookingLink,
          }),
        });

        if (emailResult.success) {
          result.sent++;
        } else {
          // Update invitation to note email failure
          await pool.query(`
            UPDATE invitations
            SET notes = $1
            WHERE dinner_id = $2 AND guest_id = $3 AND token = $4
          `, [`Email send failed: ${emailResult.error}`, id, guestId, token]);

          result.failed.push({ guestId, reason: emailResult.error || 'Email send failed' });
        }
      } catch (err) {
        result.failed.push({
          guestId,
          reason: err instanceof Error ? err.message : 'Unknown error',
        });
      }
    }

    return NextResponse.json(result);
  } catch (error) {
    console.error('Error sending invites:', error);
    return NextResponse.json(
      { error: 'Failed to send invites' },
      { status: 500 }
    );
  }
}
